# -*- coding: utf-8 -*-
"""banking_app_reviews_analysis pt.1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ztyv6sAZZRqM_Tu28R0rXA_d3LgbSghx
"""

import pandas as pd
import spacy
nlp = spacy.load('en_core_web_sm')
import time
import re
from collections import Counter
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('/content/drive/MyDrive/MSDA683/FinalProject/bank_reviews3.csv')

df.head()

print(df.keys())

df.shape

df.info()

bankrating_df = pd.DataFrame(df, columns=['bank','rating','review'])
print(bankrating_df.shape)
bankrating_df.head()

print(bankrating_df.keys())

bankrating_df.info()

bankrating_df.rating.value_counts()

bankrating_df.rating.value_counts().plot(kind='bar')
plt.savefig('/content/drive/MyDrive/MSDA683/FinalProject/bankratingcounts.jpg', bbox_inches='tight')

def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

bankrating_df['review'] = bankrating_df['review'].apply(lambda text: remove_urls(text))
bankrating_df.head()

import string
PUNCT_TO_REMOVE = string.punctuation
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', PUNCT_TO_REMOVE))

bankrating_df['review'] = bankrating_df['review'].apply(lambda text: remove_punctuation(text))
bankrating_df.head()

bankfiveStardf = bankrating_df[df['rating'] == 5]

bankfiveStardf.head()

bankfiveStarSamp = bankfiveStardf.sample(n=550)
bankfiveStarSamp.shape

start_time = time.perf_counter()
FiveStarAdj = []
FiveStarProds = []
for index, row in bankfiveStarSamp.iterrows():
  doc = nlp(row['review'])
  for ent in doc.ents:
    if ent.label_ == 'PRODUCT':
      FiveStarProds.append(str(ent).lower().capitalize())
  for token in doc:
    if token.pos_ == 'ADJ':
      FiveStarAdj.append(str(token).capitalize())
end_time = time.perf_counter()
print(f"Elapsed time: {end_time - start_time} seconds")
print(f"Found {len(FiveStarProds)} brands mentioned in {len(bankfiveStarSamp)} reviews" )

sorted_bank_Prodlist = sorted(FiveStarProds, key=str)
 top_bank_Prodlist = pd.DataFrame(Counter(sorted_bank_Prodlist).most_common(20), columns=['Product','Count'])
 print(top_bank_Prodlist)

final_list = top_bank_Prodlist

final_list = final_list.drop(index=3)

print(final_list)

plot = final_list.plot.barh(x='Product', y='Count',
                            title='Common Products Mentioned in 5-Star Reviews').invert_yaxis()
plt.savefig('/content/drive/MyDrive/MSDA683/FinalProject/commonproducts5starbanks.jpg', bbox_inches='tight')

sorted_bank_Adjlist = sorted(FiveStarAdj, key=str)
top_bank_Adjlist = pd.DataFrame(Counter(sorted_bank_Adjlist).most_common(20), columns=['Adjective','Count'])
print(top_bank_Adjlist)

plot = top_bank_Adjlist.plot.barh(x='Adjective', y='Count', color = 'green',
                            title='Common Adjectives Mentioned in 5-Star Bank Reviews').invert_yaxis()
plt.savefig('/content/drive/MyDrive/MSDA683/FinalProject/5starBANKADJ.jpg', bbox_inches='tight')

start_time = time.perf_counter()
bankFiveStarAdjOne = []
for index, row in bankfiveStarSamp.iterrows():
  doc = nlp(row['review'])
  for ent in doc.ents:
    if ent.label_ == 'PRODUCT' and str(ent).lower() == "app":
      for token in doc:
        if token.pos_ == 'ADJ':
          bankFiveStarAdjOne.append(str(token).capitalize())
end_time = time.perf_counter()
print(f"Elapsed time: {end_time - start_time} seconds")
print(bankFiveStarAdjOne)

sorted_bank_AdjlistOne = sorted(bankFiveStarAdjOne, key=str)
top_bank_AdjlistOne = pd.DataFrame(Counter(sorted_bank_AdjlistOne).most_common(20), columns=['Adjective','Count'])
print(top_bank_AdjlistOne)

start_time = time.perf_counter()
mobile_related_nouns = []

for index, row in bankfiveStarSamp.iterrows():
    doc = nlp(row['review'])
    mobile_token_indices = [token.i for token in doc if token.text.lower() == "mobile"]

    for mobile_index in mobile_token_indices:
        for token in doc[max(0, mobile_index - 5) : min(len(doc), mobile_index + 6)]:
            if token.pos_ == 'NOUN':
                mobile_related_nouns.append(str(token).capitalize())

end_time = time.perf_counter()
print(f"Elapsed time: {end_time - start_time} seconds")
print(f"Found {len(mobile_related_nouns)} mobile-related nouns in {len(bankfiveStarSamp)} reviews" )

sorted_mobile_nouns = sorted(mobile_related_nouns, key=str)
top_mobile_nouns = pd.DataFrame(Counter(sorted_mobile_nouns).most_common(20), columns=['Noun','Count'])
print(top_mobile_nouns)

if not top_mobile_nouns.empty:
    plot = top_mobile_nouns.plot.barh(x='Noun', y='Count', color = 'green',
                                title='Common Nouns Near "Mobile" in 5-Star Bank Reviews').invert_yaxis()
    plt.savefig('/content/drive/MyDrive/MSDA683/FinalProject/mobile_related_nouns_5star.jpg', bbox_inches='tight')
else:
    print("mobile-related nouns")

start_time = time.perf_counter()
app_related_adjectives = []

for index, row in bankfiveStarSamp.iterrows():
    doc = nlp(row['review'])
    app_token_indices = [token.i for token in doc if token.text.lower() == "app"]

    for app_index in app_token_indices:
        # Look for adjectives in the surrounding 5 tokens (adjust window size as needed)
        for token in doc[max(0, app_index - 5) : min(len(doc), app_index + 6)]:
            if token.pos_ == 'ADJ':
                app_related_adjectives.append(str(token).capitalize())

end_time = time.perf_counter()
print(f"Elapsed time: {end_time - start_time} seconds")
print(f"Found {len(app_related_adjectives)} app-related adjectives in {len(bankfiveStarSamp)} reviews" )

sorted_app_adjectives = sorted(app_related_adjectives, key=str)
top_app_adjectives = pd.DataFrame(Counter(sorted_app_adjectives).most_common(20), columns=['Adjective','Count'])
print(top_app_adjectives)

if not top_app_adjectives.empty:
    plot = top_app_adjectives.plot.barh(x='Adjective', y='Count', color = 'blue',
                                title='Common Adjectives Near "App" in 5-Star Bank Reviews').invert_yaxis()
    plt.savefig('/content/drive/MyDrive/MSDA683/FinalProject/app_related_adjectives_5star.jpg', bbox_inches='tight')

!pip install textblob

from textblob import TextBlob

def get_sentiment(text):
    '''
    Utility function to classify sentiment of passed tweet
    using textblob's sentiment method
    '''
    # create TextBlob object of passed tweet text
    analysis = TextBlob(text)
    # set sentiment
    if analysis.sentiment.polarity > 0:
        return 'positive'
    elif analysis.sentiment.polarity == 0:
        return 'neutral'
    else:
        return 'negative'

bankrating_df['sentiment'] = bankrating_df['review'].apply(get_sentiment)

print(bankrating_df[['review', 'sentiment']].head())

print(bankrating_df['sentiment'].value_counts())

bankrating_df['sentiment'].value_counts().plot(kind='bar', title='Sentiment Distribution of Bank Reviews')
plt.savefig('/content/drive/MyDrive/MSDA683/FinalProject/sentiment_distribution.jpg', bbox_inches='tight')
plt.show()

# prompt: create sentiment analysis of reviews that mention mobile or app

# Filter reviews that mention 'mobile' or 'app'
mobile_app_reviews_df = bankrating_df[
    bankrating_df['review'].str.contains('mobile|app', case=False, na=False)
].copy()

# Apply sentiment analysis to the filtered reviews
mobile_app_reviews_df['sentiment'] = mobile_app_reviews_df['review'].apply(get_sentiment)

print("\nSentiment analysis for reviews mentioning 'mobile' or 'app':")
print(mobile_app_reviews_df[['review', 'sentiment']].head())

print("\nSentiment distribution for reviews mentioning 'mobile' or 'app':")
print(mobile_app_reviews_df['sentiment'].value_counts())

# Plot the sentiment distribution for these filtered reviews
mobile_app_reviews_df['sentiment'].value_counts().plot(
    kind='bar', title='Sentiment Distribution of Reviews Mentioning Mobile or App'
)
plt.savefig('/content/drive/MyDrive/MSDA683/FinalProject/mobile_app_sentiment_distribution.jpg', bbox_inches='tight')
plt.show()

# prompt: top 20 adjectives used in negative sentiment reviews along with their counts

# Filter for negative sentiment reviews
negative_reviews_df = bankrating_df[bankrating_df['sentiment'] == 'negative'].copy()

# Extract adjectives from negative reviews
start_time = time.perf_counter()
negative_adjectives = []
for index, row in negative_reviews_df.iterrows():
    doc = nlp(row['review'])
    for token in doc:
        if token.pos_ == 'ADJ':
            negative_adjectives.append(str(token).capitalize())

end_time = time.perf_counter()
print(f"Elapsed time: {end_time - start_time} seconds")
print(f"Found {len(negative_adjectives)} adjectives in {len(negative_reviews_df)} negative reviews" )

# Count the occurrences of each adjective and get the top 20
sorted_negative_adjectives = sorted(negative_adjectives, key=str)
top_negative_adjectives = pd.DataFrame(
    Counter(sorted_negative_adjectives).most_common(20),
    columns=['Adjective','Count']
)

print("\nTop 20 Adjectives in Negative Sentiment Reviews:")
print(top_negative_adjectives)

# Plot the top 20 negative adjectives
if not top_negative_adjectives.empty:
    plot = top_negative_adjectives.plot.barh(
        x='Adjective',
        y='Count',
        color = 'red',
        title='Common Adjectives Mentioned in Negative Sentiment Reviews'
    ).invert_yaxis()
    plt.savefig('/content/drive/MyDrive/MSDA683/FinalProject/negative_adjectives.jpg', bbox_inches='tight')
    plt.show()
else:
    print("No adjectives found in negative reviews.")

negative_mobile_app_reviews_df = mobile_app_reviews_df[mobile_app_reviews_df['sentiment'] == 'negative'].copy()

print("\nNegative Sentiment Reviews mentioning 'mobile' or 'app':")
negative_mobile_app_reviews_df

negative_mobile_app_reviews_df.to_csv('/content/drive/MyDrive/MSDA683/FinalProject/negative_mobile_app_reviews.csv', index=False)
print("\nSaved negative mobile/app reviews to 'negative_mobile_app_reviews.csv'")