# -*- coding: utf-8 -*-
"""banking_app_reviews_analysis pt.2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jgvczk5eaZdzWTuRgC--LG3HSKQ7C49
"""

import pandas as pd
import spacy
nlp = spacy.load('en_core_web_sm')
import time
import re
from collections import Counter
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('/content/drive/MyDrive/MSDA683/FinalProject/pak_app_bank_reviews.csv')

df.head()

print(df.keys())

df.shape

df.info()

pakmobilebankrating_df = pd.DataFrame(df, columns=['app','content','score','at'])
print(pakmobilebankrating_df.shape)
pakmobilebankrating_df.head()

print(pakmobilebankrating_df.keys())

pakmobilebankrating_df.info()

pakmobilebankrating_df.score.value_counts()

pakmobilebankrating_df.score.value_counts().plot(kind='bar')
plt.savefig('/content/drive/MyDrive/MSDA683/FinalProject/PAKMOBILEbankratingcounts.jpg', bbox_inches='tight')

def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

pakmobilebankrating_df['content'] = pakmobilebankrating_df['content'].apply(lambda text: remove_urls(text))
pakmobilebankrating_df.head()

import string
PUNCT_TO_REMOVE = string.punctuation
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', PUNCT_TO_REMOVE))

pakmobilebankrating_df['content'] = pakmobilebankrating_df['content'].apply(lambda text: remove_punctuation(text))
pakmobilebankrating_df.head()

PAKMOBILEbankONEstardf = pakmobilebankrating_df[df['score'] == 1]

PAKMOBILEbankONEstardf.head()

start_time = time.perf_counter()
FiveStarAdj = []
FiveStarProds = []
for index, row in PAKMOBILEbankONEstardf.iterrows():
  doc = nlp(row['content'])
  for ent in doc.ents:
    if ent.label_ == 'PRODUCT':
      FiveStarProds.append(str(ent).lower().capitalize())
  for token in doc:
    if token.pos_ == 'ADJ':
      FiveStarAdj.append(str(token).capitalize())
end_time = time.perf_counter()
print(f"Elapsed time: {end_time - start_time} seconds")
print(f"Found {len(FiveStarProds)} brands mentioned in {len(PAKMOBILEbankONEstardf)} reviews" )

sorted_PAKMOBILEbank_Prodlist = sorted(FiveStarProds, key=str)
 top_PAKMOBILEbank_Prodlist = pd.DataFrame(Counter(sorted_PAKMOBILEbank_Prodlist).most_common(20), columns=['Product','Count'])
 print(top_PAKMOBILEbank_Prodlist)

PAKMOBILEfinal_PRODUCTlist = top_PAKMOBILEbank_Prodlist

PAKMOBILEfinal_PRODUCTlist = PAKMOBILEfinal_PRODUCTlist.drop(index=11)

print(PAKMOBILEfinal_PRODUCTlist)

plot = PAKMOBILEfinal_PRODUCTlist.plot.barh(x='Product', y='Count',
                            title='Common Products Mentioned in 1-Star Reviews').invert_yaxis()
plt.savefig('/content/drive/MyDrive/MSDA683/FinalProject/PAKMOBILEcommonproducts1starbanks.jpg', bbox_inches='tight')

sorted_PAKMOBILEbank_Adjlist = sorted(FiveStarAdj, key=str)
top_PAKMOBILEbank_Adjlist = pd.DataFrame(Counter(sorted_PAKMOBILEbank_Adjlist).most_common(20), columns=['Adjective','Count'])
print(top_PAKMOBILEbank_Adjlist)

plot = top_PAKMOBILEbank_Adjlist.plot.barh(x='Adjective', y='Count', color = 'green',
                            title='Common Adjectives Mentioned in 1-Star Bank Reviews').invert_yaxis()
plt.savefig('/content/drive/MyDrive/MSDA683/FinalProject/PAKMOBILE1starBANKADJ.jpg', bbox_inches='tight')

start_time = time.perf_counter()
PAKMOBILEbankFiveStarAdjOne = []
for index, row in PAKMOBILEbankONEstardf.iterrows():
  doc = nlp(row['content'])
  for ent in doc.ents:
    if ent.label_ == 'PRODUCT' and str(ent).lower() == "app":
      for token in doc:
        if token.pos_ == 'ADJ':
          PAKMOBILEbankONEstarAdjOne.append(str(token).capitalize())
end_time = time.perf_counter()
print(f"Elapsed time: {end_time - start_time} seconds")
print(PAKMOBILEbankONEstarAdjOne)

sorted_PAKMOBILEbank_AdjlistOne = sorted(PAKMOBILEbankONEstarAdjOne, key=str)
top_PAKMOBILEbank_AdjlistOne = pd.DataFrame(Counter(sorted_PAKMOBILEbank_AdjlistOne).most_common(20), columns=['Adjective','Count'])
print(top_PAKMOBILEbank_AdjlistOne)

start_time = time.perf_counter()
PAKmobile_related_nouns = []

for index, row in PAKMOBILEbankONEstardf.iterrows():
    doc = nlp(row['content'])
    mobile_token_indices = [token.i for token in doc if token.text.lower() == "mobile"]

    for mobile_index in mobile_token_indices:
        for token in doc[max(0, mobile_index - 5) : min(len(doc), mobile_index + 6)]:
            if token.pos_ == 'NOUN':
                PAKmobile_related_nouns.append(str(token).capitalize())

end_time = time.perf_counter()
print(f"Elapsed time: {end_time - start_time} seconds")
print(f"Found {len(PAKmobile_related_nouns)} mobile-related nouns in {len(PAKMOBILEbankONEstardf)} reviews" )

sorted_PAKmobile_nouns = sorted(PAKmobile_related_nouns, key=str)
top_PAKmobile_nouns = pd.DataFrame(Counter(sorted_PAKmobile_nouns).most_common(20), columns=['Noun','Count'])
print(top_PAKmobile_nouns)

if not top_PAKmobile_nouns.empty:
    plot = top_PAKmobile_nouns.plot.barh(x='Noun', y='Count', color = 'green',
                                title='Common Nouns Near "Mobile" in 1-Star Bank Reviews').invert_yaxis()
    plt.savefig('/content/drive/MyDrive/MSDA683/FinalProject/PAKmobile_related_nouns_1star.jpg', bbox_inches='tight')
else:
    print("PAKmobile-related nouns")

start_time = time.perf_counter()
PAKMOBILEapp_related_adjectives = []

for index, row in PAKMOBILEbankONEstardf.iterrows():
    doc = nlp(row['content'])
    app_token_indices = [token.i for token in doc if token.text.lower() == "app"]

    for app_index in app_token_indices:
        # Look for adjectives in the surrounding 5 tokens (adjust window size as needed)
        for token in doc[max(0, app_index - 5) : min(len(doc), app_index + 6)]:
            if token.pos_ == 'ADJ':
                PAKMOBILEapp_related_adjectives.append(str(token).capitalize())

end_time = time.perf_counter()
print(f"Elapsed time: {end_time - start_time} seconds")
print(f"Found {len(PAKMOBILEapp_related_adjectives)} app-related adjectives in {len(PAKMOBILEbankONEstardf)} reviews" )

sorted_PAKMOBILEapp_adjectives = sorted(PAKMOBILEapp_related_adjectives, key=str)
top_PAKMOBILEapp_adjectives = pd.DataFrame(Counter(sorted_PAKMOBILEapp_adjectives).most_common(20), columns=['Adjective','Count'])
print(top_PAKMOBILEapp_adjectives)

if not top_PAKMOBILEapp_adjectives.empty:
    plot = top_PAKMOBILEapp_adjectives.plot.barh(x='Adjective', y='Count', color = 'blue',
                                title='Common Adjectives Near "App" in 1-Star Bank Reviews').invert_yaxis()
    plt.savefig('/content/drive/MyDrive/MSDA683/FinalProject/PAKMOBILEapp_related_adjectives_1star.jpg', bbox_inches='tight')

!pip install textblob

from textblob import TextBlob

def get_sentiment(text):
    '''
    Utility function to classify sentiment of passed tweet
    using textblob's sentiment method
    '''
    # create TextBlob object of passed tweet text
    analysis = TextBlob(text)
    # set sentiment
    if analysis.sentiment.polarity > 0:
        return 'positive'
    elif analysis.sentiment.polarity == 0:
        return 'neutral'
    else:
        return 'negative'

pakmobilebankrating_df['sentiment'] = pakmobilebankrating_df['content'].apply(get_sentiment)

print(pakmobilebankrating_df[['content', 'sentiment']].head())

print(pakmobilebankrating_df['sentiment'].value_counts())

pakmobilebankrating_df['sentiment'].value_counts().plot(kind='bar', title='Sentiment Distribution of Bank Reviews')
plt.savefig('/content/drive/MyDrive/MSDA683/FinalProject/pakmobilesentiment_distribution.jpg', bbox_inches='tight')
plt.show()

# prompt: create sentiment analysis of reviews that mention mobile or app

# Filter reviews that mention 'mobile' or 'app'
PAKmobile_app_reviews_df = pakmobilebankrating_df[
    pakmobilebankrating_df['content'].str.contains('mobile|app', case=False, na=False)
].copy()

# Apply sentiment analysis to the filtered reviews
PAKmobile_app_reviews_df['sentiment'] = PAKmobile_app_reviews_df['content'].apply(get_sentiment)

print("\nSentiment analysis for reviews mentioning 'mobile' or 'app':")
print(PAKmobile_app_reviews_df[['content', 'sentiment']].head())

print("\nSentiment distribution for reviews mentioning 'mobile' or 'app':")
print(PAKmobile_app_reviews_df['sentiment'].value_counts())

# Plot the sentiment distribution for these filtered reviews
PAKmobile_app_reviews_df['sentiment'].value_counts().plot(
    kind='bar', title='Sentiment Distribution of Reviews Mentioning Mobile or App'
)
plt.savefig('/content/drive/MyDrive/MSDA683/FinalProject/PAKmobile_app_sentiment_distribution.jpg', bbox_inches='tight')
plt.show()

# prompt: top 20 adjectives used in negative sentiment reviews along with their counts

# Filter for negative sentiment reviews
PAKMOBILEnegative_reviews_df = pakmobilebankrating_df[pakmobilebankrating_df['sentiment'] == 'negative'].copy()

# Extract adjectives from negative reviews
start_time = time.perf_counter()
PAKMOBILEnegative_adjectives = []
for index, row in PAKMOBILEnegative_reviews_df.iterrows():
    doc = nlp(row['content'])
    for token in doc:
        if token.pos_ == 'ADJ':
            PAKMOBILEnegative_adjectives.append(str(token).capitalize())

end_time = time.perf_counter()
print(f"Elapsed time: {end_time - start_time} seconds")
print(f"Found {len(PAKMOBILEnegative_adjectives)} adjectives in {len(PAKMOBILEnegative_reviews_df)} negative reviews" )

# Count the occurrences of each adjective and get the top 20
sorted_PAKMOBILEnegative_adjectives = sorted(PAKMOBILEnegative_adjectives, key=str)
top_PAKMOBILEnegative_adjectives = pd.DataFrame(
    Counter(sorted_PAKMOBILEnegative_adjectives).most_common(20),
    columns=['Adjective','Count']
)

print("\nTop 20 Adjectives in Negative Sentiment Reviews:")
print(top_PAKMOBILEnegative_adjectives)

# Plot the top 20 negative adjectives
if not top_PAKMOBILEnegative_adjectives.empty:
    plot = top_PAKMOBILEnegative_adjectives.plot.barh(
        x='Adjective',
        y='Count',
        color = 'red',
        title='Common Adjectives Mentioned in Negative Sentiment Reviews'
    ).invert_yaxis()
    plt.savefig('/content/drive/MyDrive/MSDA683/FinalProject/PAKMOBILEnegative_adjectivesinsentimentanalysis.jpg', bbox_inches='tight')
    plt.show()
else:
    print("No adjectives found in negative reviews.")

PAKMOBILEnegative_mobile_app_reviews_df = pakmobilebankrating_df[pakmobilebankrating_df['sentiment'] == 'negative'].copy()

print("\nNegative Sentiment Reviews mentioning 'mobile' or 'app':")
PAKMOBILEnegative_mobile_app_reviews_df

PAKMOBILEnegative_mobile_app_reviews_df.to_csv('/content/drive/MyDrive/MSDA683/FinalProject/PAKMOBILEnegative_mobile_app_reviews.csv', index=False)
print("\nSaved negative mobile/app reviews to 'negative_mobile_app_reviews.csv'")